### ISSUE TITLE
Product - hide empty fields

### ISSUE THREAD

**Issue by logicwisesoftware** [logicwisesoftware/zcova#177]
[![Screenshot_2022-07-18_06-58-29.png](https://mrkr.io/s/62d504951f50aae86fa64fab/2)](https://mrkr.io/s/62d504951f50aae86fa64fab/0)

If the fields are empty, hide them

---

**Reported by:** Isabel (isabel@zcova.com) - [Contact via Marker.io](https://app.marker.io/i/62d504951f50aae86fa64fae_0fc8abc7517902d0?comments=1)

**Source URL:** [https://zcova-uat.com/necklaces/selected-necklace/14?cartID=53&cartType=jewellery](https://zcova-uat.com/necklaces/selected-necklace/14?cartID=53&cartType=jewellery)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62d504951f50aae86fa64fae_0fc8abc7517902d0)

<table><tr><td><strong>Browser</strong></td><td>Chrome 103.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 800</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.13.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>2088 x 1300</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d504951f50aae86fa64fae_0fc8abc7517902d0) - This issue was marked as resolved in Marker.io.

**Comment by isabelzcova** [comment]
<img width="990" alt="empty" src="https://user-images.githubusercontent.com/108924987/180114502-46e4246d-4572-4523-a897-73dad4e39c4b.png">
Please remove from Step 3 and Cart as well

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d504951f50aae86fa64fae_0fc8abc7517902d0) - This issue was marked as resolved in Marker.io.

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d504951f50aae86fa64fae_0fc8abc7517902d0) - This issue was marked as open in Marker.io.

**Comment by isabelzcova** [comment]
Empty fields still appearing in Cart and various products

This ring still has it
https://zcova-uat.com/settings/selected-setting/10

**Comment by salimi-my** [comment]
Fixed

**Comment by logicwisesoftware** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/62d504951f50aae86fa64fae_0fc8abc7517902d0) - This issue was marked as resolved in Marker.io.
